site_name: 我的知识库
theme:
  name: material            # 使用 Material 主题
  features:
    - navigation.tabs
    - search.suggest
plugins:
  - search
nav:
  - 首页: index.md
  - 笔记: 
      - Python: notes/python.md
  - 面试题: interview/algorithms.md